CREATE DATABASE arqdedados;
USE arqdedados;

CREATE TABLE Members_Adress (
	MEMBER_NUM INT NOT NULL,
    MEMBER_NAME VARCHAR(75) NOT NULL,
    MEMBER_ADRESS_1 VARCHAR(75),
    MEMBER_ADRESS_2 VARCHAR(75),
    PRIMARY KEY (MEMBER_NUM)
);

CREATE TABLE Registred_Members (
	MEMBER_NUM INT PRIMARY KEY NOT NULL,
    MEMBER_NAME VARCHAR(75) NOT NULL
);

CREATE TABLE Dinners_Info (
	DINNER_NUM VARCHAR(6) PRIMARY KEY NOT NULL,
    DINNER_DATE DATETIME NOT NULL
);

CREATE TABLE Cardapio (
	FOOD_CODE VARCHAR(5) PRIMARY KEY NOT NULL,
    FOOD_DESCRIPTION VARCHAR(85) NOT NULL
);

CREATE TABLE Venues (
	VENUE_CODE VARCHAR(4) PRIMARY KEY NOT NULL,
    VENUE_DESCRIPTION VARCHAR(60)
);

CREATE TABLE Dinner_Service (
	MEMBER_NUM INT NOT NULL,
    MEMBER_NAME VARCHAR(45),
    MEMBER_ADRESS VARCHAR(75),
    DINNER_NUM VARCHAR(6),
    DINNER_DATE DATETIME,
    VENUE_CODE VARCHAR(4),
    VENUE_DESCRIPTION VARCHAR(60),
    FOOD_CODE VARCHAR(5),
    FOOD_DESCRIPTION VARCHAR(85),
    FOREIGN KEY (MEMBER_NUM) REFERENCES Registred_Members(MEMBER_NUM),
    FOREIGN KEY (DINNER_NUM) REFERENCES Dinners_Info(DINNER_NUM),
    FOREIGN KEY (VENUE_CODE) REFERENCES Venues(VENUE_CODE),
    FOREIGN KEY (FOOD_CODE) REFERENCES Cardapio(FOOD_CODE)
);

CREATE TABLE Dinner_Requests (
	Requests_id INT PRIMARY KEY AUTO_INCREMENT,
	MEMBER_NUM INT NOT NULL,
    DINNER_NUM VARCHAR(6) NOT NULL,
    FOOD_CODE VARCHAR(5) NOT NULL,
    FOREIGN KEY (MEMBER_NUM) REFERENCES Dinner_Service(MEMBER_NUM),
    FOREIGN KEY (DINNER_NUM) REFERENCES Dinners_Info(DINNER_NUM),
    FOREIGN KEY (FOOD_CODE) REFERENCES Cardapio(FOOD_CODE)
);

CREATE TABLE Restructured_Dinner_Service (
	DINNER_DATE DATETIME NOT NULL,
    DINNER_NUM VARCHAR(6) PRIMARY KEY NOT NULL,
    MEMBER_NUM INT NOT NULL,
    VENUE_CODE VARCHAR(4) NOT NULL,
    FOREIGN KEY (DINNER_NUM) REFERENCES Dinners_Info(DINNER_NUM),
    FOREIGN KEY (VENUE_CODE) REFERENCES Venues(VENUE_CODE),
    FOREIGN KEY (MEMBER_NUM) REFERENCES Registred_Members(MEMBER_NUM)
);